### PR TITLE
Print valid json to stdout and remove print lines that can not suppress by cmdline args

### PR DESCRIPTION
**Pull request by basvandervlies**

### CODE REVIEW

**Comment by waxie** [comment]
?

**Comment by basvandervlies** [comment]
ramon just see my fork.  We have a lot of changes and cmt 2.0 is in production at SURFsara

**Comment by waxie** [comment]
that's great to hear! But why did you close the pull request, you don't want it merged anymore? Or did you close it by accident

**Comment by basvandervlies** [comment]
@waxie This is one big pull request with all the changes that we have made. I just pushed the wrong button and submitted it to your repo.  You can merge my master branch with yours to be up to date.  We are still doing changes to improve it. In general everything works great. Thanks

**Pull request closed without merging**
