### PR TITLE
cmt client module patch

### PR DESCRIPTION
**Pull request by basvandervlies**
patch cmt_client/cmt.py so it can be run in a python program added an example for this setup

### CODE REVIEW

**Comment by waxie** [comment]
Hi Bas,

This seems like a better way of handling the args for the client module.

I'm currently without a working computer so it's hard to judge, but at a glance it seems like line 441 should be differently.

This:

 `if os.path.exists( DEFAULT_CONFIG_FILE ):`

Should be:

`if os.path.exists( self.temp_args['config_file'] ):`

Do you agree?

Cheers,
- Ramon

**Comment by basvandervlies** [comment]
Ramon,

 I am also not near a computer and on holidays,. Your suggestion looks ok for me

Cheers

> On 23 dec. 2015, at 10:39, Ramon Bastiaans notifications@github.com wrote:
> 
> Hi Bas,
> 
> This seems like a better way of handling the args for the client module.
> 
> I'm currently without a working computer so it's hard to judge, but at a glance it seems like line 441 should be differently.
> 
> This:
> 
> if os.path.exists( DEFAULT_CONFIG_FILE ):
> 
> Should be:
> 
> if os.path.exists( self.temp_args['config_file'] ):
> 
> Do you agree?
> 
> Cheers,
> 
>   • Ramon
> —
> Reply to this email directly or view it on GitHub.

## 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by waxie** [comment]
Bas,

Could you modify the pull request to incorporate my suggestion regarding the config file line?

I don't think I can modify your pull request commit myself.

After that I can merge the pull request.

Cheers,
- Ramon

**Comment by basvandervlies** [comment]
Ramon I will update my pull request.

**Comment by basvandervlies** [comment]
Ramon thanks.   Dennis has rewrote a lot and you have merged all changes ;-). Are you still interested in cmt. We want to move it the public gitlab repo under surfsara.   We forsee a lot of code changes ;-)

**Pull request merged**
